### ISSUE TITLE
Prior Year Schedules

### ISSUE THREAD

**Issue by michael-terhorst** [lbenz730/ncaahoopR#34]
Hi Luke - Two quick items:

1. get_master_schedule might be having an issue pulling up the first day of the 2018-19 season for example: 
get_master_schedule("2018-11-06") ----> isn't working
get_master_schedule("2018-12-06") ----> for example is working
Am I doing something incorrect, or any guidance on how to get the game_ids from that date?

2. Do you possibly have code or a link to get the full season of game_ids/schedule for prior years?  I'm still new to R and have been trying to come up with various codes to get at this in different ways, but from a QC perspective would be interested to know if there was a faster way as well.

Thanks so much!
- Michael

**Comment by lbenz730** [comment]
Hi Michael. Yes the `get_master_schedule` code could be a little finicky going back in time as ESPN often changes their underlying HTML structure. Check out this repository for master schedules by season (https://github.com/lbenz730/ncaahoopR_data). You can always get a full season of data from there or by doing something like this:

```
library(ncaahoopR)

master_schedule <- NULL

for(i in 1:nrow(ids)) {
     schedule <- get_schedule(ids$team[i],  year)
     master_schedule <- rbind(master_schedule, schedule)
}
```

Note there may have to be some try-error catching if year isn't current since ESPN doesn't archive 100% of schedules. This script may help you out (https://github.com/lbenz730/ncaahoopR_data/blob/master/old_schedules.R). 

I can try and throw together something that would help you traverse this data repo if that would be helpful.
