### ISSUE TITLE
error running get_roster

### ISSUE THREAD

**Issue by ehrenj1** [lbenz730/ncaahoopR#41]
I tried to do ncaahoopR::get_roster("Kansas") and it spit out the Kennesaw State roster.  It looks like ESPN might have changed the links in their system.  For example "kennesaw-st-owls" is now "kennesaw-state-owls".  Now the create_ids_df function appears to be the source of this error.  I went ahead and updated the "ids.csv" file from lbenz730/NCAA_Hoops_Play_By_Play by changing some of the links that appeared to be changed, and now it appears to be working. 
[ids_JE.zip](https://github.com/lbenz730/ncaahoopR/files/4465090/ids_JE.zip)

**Comment by lbenz730** [comment]
Thanks for bringing this up. I realized that ids.csv was an outdated package so I added a flat csv of the updated ids.rda that is loaded when you load the package via `library(ncaahoopR)`. When you call functions via ncaahoopR:: it doesn't fully load the attached data which is why it was looking for this information elsewhere. Should be fixed now!
