### ISSUE TITLE
Errors with Get Schedule/ Get PBP

### ISSUE THREAD

**Issue by akaushik1998** [lbenz730/ncaahoopR#46]
Hi Luke,

When I try to pull schedule's for teams I get the following error-- 

`get_schedule("Duke")`
`Error in XML::readHTMLTable(RCurl::getURL(url))[[1]] : subscript out of bounds`

Additionally when I try to get a team's PBP I get the following error: 

`get_pbp("Duke")`
`Getting Game IDs: Duke`
`Error in XML::readHTMLTable(RCurl::getURL(url))[[1]] :  subscript out of bounds`

If I feed in a game id then I don't get the same error but I get the following error if I try to get historical game ids : 

`get_game_ids("Duke", season = "2017-18")`
`Error in if (reg_flag > 1) { : argument is of length zero`

Appreciate any help,
Aditya

**Comment by lbenz730** [comment]
Hey Aditya, thanks for bringing this to my attention. Your first issue isn't so much an issue with the package. When no season argument is supplied, the package assumes to use the current season (now "2020-21") which doesn't yet have schedules available. You should supply season = "2019-20" if you want this most recent season's data. 

That being said, ESPN is always changing it's underlying html, which is why you were getting the 2nd error. I've fixed that and added a warning message to the user to use 2019-20 in place of current season for time being. Let me know where else the package breaks if you find any places, as whenever ESPN changes their html, it causes these minor hiccups in a few spots. 

Thanks,
Luke

**Comment by iprva** [comment]
Hey Luke,

I'm getting the same errors with get_schedule, get_pbp, & get_game_ids.

In addition, when I try to pull a single game's play-by-play data prior to the 2019-2020 season:

```
get_pbp_game(401123419)
Scraping Data for Game: 1 of 1
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'http://barttorvik.com/2019_rosters.json': HTTP status was '403 Forbidden'
```

I'm not sure if this is an issue on my end, your end, or Bart's end.

Thanks,
Ian

**Comment by lbenz730** [comment]
Hey Ian,

I wasn't able to replicate the issue w/ get_pbp_game, so I think that could be on your end? I just pushed some changes to fix the other issue regarding past schedule/pbp/game_id. Thanks for the heads up! Let me know if you still can't get it working after re-install.

Luke

**Comment by iprva** [comment]
I now appear to be having issues re-installing the package:

```
package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'ncaahoopR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’
```

**Comment by lbenz730** [comment]
Probably related to this issue:
https://stackoverflow.com/questions/41918543/warning-in-install-packages-cannot-remove-prior-installation-of-package-data

Try restarting your R session fresh and then try install.

**Comment by iprva** [comment]
Was able to install by selecting 3: None. Functions work properly!

```
Downloading GitHub repo lbenz730/ncaahoopR@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: rlang  (0.4.6 -> 0.4.7) [CRAN]
5: pillar (1.4.4 -> 1.4.6) [CRAN]
6: vctrs  (0.3.1 -> 0.3.2) [CRAN]
7: tibble (3.0.1 -> 3.0.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
```

Still having the issue with Bart's site. I'm curious if he has blocked my scraping attempts.
