### ISSUE TITLE
PBP and Game ID Error for Most Seasons

### ISSUE THREAD

**Issue by z-feldman** [lbenz730/ncaahoopR#67]
Testing this and the PBP functions back to 2010, the only seasons I **don't** get this error (usually different numbers of Sizes for different seasons) are 2012-2013, 2020-2021, and 2021-2022. However, the seasons that return an error are different for different teams

`get_game_ids("Ohio State", season = "2016-2017")
Error: Tibble columns must have compatible sizes.
* Size 30: Existing data.
* Size 29: Column `date`.
i Only values of size one are recycled.`

**Comment by lbenz730** [comment]
Ok i think this bug is now fixed if you take a fresh install of the package. Let me know if you run into any other issues. Also, if you are working a lot of data and want it pre-scraped, take a look at https://github.com/lbenz730/ncaahoopR_data. I'll have the last few days worth of data up in a few minutes.
